### ISSUE TITLE
Cleared history and then major problems.

### ISSUE THREAD

**Issue by hwndx** [Crunch/Crunch-2#104]
I upgraded the beta then cleared all my project history, after clearing the history I closed the program then later tried to reopen it to what I call a blank window:

![ss](https://cloud.githubusercontent.com/assets/3639344/10775608/e9b8b832-7cd7-11e5-84cd-04c695673990.png)

Then just for the sanity, I tried dragging a folder over and it worked but not as it should:

![ss2](https://cloud.githubusercontent.com/assets/3639344/10775629/206eb7d2-7cd8-11e5-8146-36ed4cc07224.png)

Once that happened, I attempted to click on one of the less files and this is how it displayed:

![ss3](https://cloud.githubusercontent.com/assets/3639344/10775661/6029cb32-7cd8-11e5-8e9f-b6bb61ec169a.png)

Also to note, I tried removing/running a system cleaner and doing a clean install. I also tried going back to my earlier system restore point and re-installing but the same thing still happens.

**Comment by matthew-dean** [comment]
> I upgraded the beta then cleared all my project history

Do you mean you removed every project folder?

It looks like what happened was, first a JavaScript error, which basically gives you basically a blank web canvas. That would prevent the code loading that prevents navigating to a folder when you drag it in. So, at that point, you're basically browsing local folders. Not that that info is that helpful, except to say that all those behaviors are basically one error, which basically sounds like a bug in removing all projects.

As far as running a system cleaner, it looks like the uninstaller does not remove localstorage, which is your project settings.

That *may* be at: ```~/Library/Application/Support/Crunch 2``` on a Mac and ```C:\Users\%USERNAME%\AppData\Local\Chromium\User Data\Default``` on Windows.

I'll see if I can think of a more elegant recovery solution for non-recoverable errors.

**Comment by hwndx** [comment]
No. I removed the project folders from the history, not the actual folders on my computer.

But, I did remove the cached configuration and settings, reinstalled and it started working.

**Comment by matthew-dean** [comment]
Okay, I think I have a pretty decent fix for this.

First, I fixed the actual bug, which was thrown by removing a folder and adding back the same folder in the same app session.

Better than that, uncaught errors show a prompt letting you know Crunch needs to close. If, when you restart, ANOTHER exception is thrown before the app even finishes loading (such as in your case), then it's probably an issue with corrupted settings. In that event, it will prompt that Crunch needs to clear all settings and close again. After that, it will start like a fresh install. That does unfortunately mean you will have to re-activate Crunch Pro (if that's what you happen to be using), but that's not as bad as the behavior you were seeing, and it shouldn't require someone to manually delete their local settings.

Marking as fixed in the codebase. The fix will be in the next release.
