### ISSUE TITLE
SASS support

### ISSUE THREAD

**Issue by nblackburn** [Crunch/Crunch-2#155]
Adding SASS support would be good as it's just as popular as LESS.

**Comment by matthew-dean** [comment]
@nblackburn An early build of Crunch 2 had SASS support. Libsass integration is tricky however. Because it's not JS-based, it required a lot of hacks and ended up being super-slow. I took it out to get to a stable point, but it's one of the things I plan on looking at next.

**Comment by nblackburn** [comment]
SASS has been rewritten in C and has node bindings available: https://github.com/sass/node-sass.

**Comment by matthew-dean** [comment]
Yes, I know. This is what I'm referring to. However: NWjs requires custom compiling of C/C++ Add ons (http://docs.nwjs.io/en/latest/For%20Users/Advanced/Use%20Native%20Node%20Modules/#use-native-node-modules).

Along with that, error messages cannot be captured in JS like they can with pretty much every other compiler. They're piped directly to STDOUT, so that meant capturing all STDOUT messages, and parsing it to discover which file is being referred to. It was pretty much working, but capturing STDOUT added it's own side-effects.

Unfortunately, all the compilers assume command-line dumps to a greater or lesser degree (I guess no one envisioned that an app might want to read these errors and make sense of them), so this kind of manual parsing per compiler is necessary in order to be able to link to the actual file/line in Crunch 2. I'm hoping to add some more robust tests so that I can make sure that any update to a library doesn't change the error output structure.

Because of this, I can only integrate one compiler at a time, and SASS is the most divergent from any of the other compilers present.

**Comment by matthew-dean** [comment]
Despite my grumbling about the work involved, Sass will come. :-)

**Comment by nblackburn** [comment]
I just thought it would be important as it's WAY more commonly used than Stylus.

**Comment by matthew-dean** [comment]
It is. I don't disagree. Stylus was just trivial to add. It pretty much worked out of the gate, and the error output was a well-structured JS object (thanks, Stylus!)

**Comment by nblackburn** [comment]
Yeah, Stylus is one of the better designed ones i have come across.

**Comment by matthew-dean** [comment]
Oh, I forgot. The other reason SASS isn't a part of IDEs like this one is because SASS doesn't want to support it. See: https://github.com/sass/node-sass/issues/1328

Their build process fails on anything other than default, command-line Node.js.

**Comment by matthew-dean** [comment]
On a whim, I decided to go back and update the emscripten version of sass.js to see if there are any improvements there. There are! The first compile takes a while, but subsequent compiles are quite fast (some caching going on?). I may actually release this.

**Comment by matthew-dean** [comment]
Proof:
<img width="1231" alt="screen shot 2016-01-22 at 5 18 06 pm" src="https://cloud.githubusercontent.com/assets/414752/12527208/3bed534a-c12c-11e5-82aa-f057ecf512c5.png">

**Comment by matthew-dean** [comment]
Done.
