### ISSUE TITLE
CSS calc function problem

### ISSUE THREAD

**Issue by jwasiak** [Crunch/Crunch-2#195]
width: calc(100% - 12px); is converted to width: calc(88%);

**Comment by TommyTheBlackbird** [comment]
This is about Less and not Crunch, because it's the way Less compiler resolves your formula. Which is right anyway cause Less is a css PRE-compiler, so it has no clue of how many pixels will be the 100% so it can't subtract absolute pixel value.
You are looking for a real-time CSS calculation, so it's a misconception of how Less (or Sass or others) works.

**Comment by jwasiak** [comment]
Thanks, I found the solution meantime
width: calc(~"100% - 22px");
