### ISSUE TITLE
CSS not minified

### ISSUE THREAD

**Issue by TommyTheBlackbird** [Crunch/Crunch-2#46]
It seems CSS is not minified by default. I can't find where can I activate this option (also to turn off generate source map file). I edited manually the JSON ".crunch" file in the project folder, but didn't work.

**Comment by TommyTheBlackbird** [comment]
I've finally found the output options in the cog wheel next to the css file link in the treeview clicking  the crunch icon in an open file tab (pretty hidden). I think it would have much more sense to have the output options in the general preferences, or to place the cog wheel next to the project in the tree (or the project root node).

**Comment by Pantyboy** [comment]
If you have a long filename, because the (grey coloured) area on the left isn't resizable, you don't see the cog.

**Comment by matthew-dean** [comment]
I don't think you're wrong that the discovery is not perfect, based on other feedback. The reason it's not in general preferences is that, unlike Crunch 1, settings are saved at the project level, which reduces code conflicts when working in teams. And the reason it's next to the output file is because the eventual goal is to support multiple outputs, such as building an un-minified and minified file at the same time.

We'll try a better solution, though.

**Comment by matthew-dean** [comment]
@Pantyboy That's probably a bug. I'm thinking that, rather than a cog, the top portion of the Crunchable needs to be a bit more prominent, with a labeled "Options" for each output. There's often not a lot of files in a project, so it could even have an accordion to change options in place. What would you guys think of that?
