### ISSUE TITLE
Save Options, Line Number & Tab Icon issues

### ISSUE THREAD

**Issue by Pantyboy** [Crunch/Crunch-2#48]
You are probably aware of these but I thought I'd check in case.

I've attached a screenshot to illustrate the issues.

1. The cog, next to the filename, to select the options for file saving isn't visible with long filenames. Although there is a scrollbar available at the bottom of the treeview, would it be possible to have the option window open on first save to .css file?

2. Losing part of the first character of a line.
This happens when the line numbers hit double figures. Also, first line number appears to be an "S".

3. Icon not at end of tab.

![crunch-screenshot](https://cloud.githubusercontent.com/assets/6214205/9683280/873360ae-5306-11e5-981a-6d8e7fcb12ba.jpg)

**Comment by amatecha** [comment]
Good timing, I was just going to file an issue on item 2 that you mentioned as I had the same issue.

I was able to restore the proper width of the line-numbers bar by collapsing and expanding one of the selector trees.

**Comment by matthew-dean** [comment]
I'd noted the problem with the line numbers but hadn't filed an issue yet, so thanks for that.

The issue with the cog placement is tracked elsewhere. 

The thing with the icon I've never seen before, so that's a neat new bug. ;)

In the future, can you open separate issues for each issue? That way I can mark them closed when each are addressed, and can reference what's finished in the releases. How it is now is okay though.

**Comment by Pantyboy** [comment]
Hi Matt

I'll make sure each issue is separate in future.

Shall I put the line numbers and the icon issues into different posts so this one can be closed/deleted?

**Comment by matthew-dean** [comment]
@Pantyboy If you're willing to take the time, that'd be great!

**Comment by Pantyboy** [comment]
@matthew-dean 

No problem.

I'll leave the cog issue out as that one is already on your radar.

**Comment by Pantyboy** [comment]
I've just split up the issues and I'll close this post.
