### ISSUE TITLE
Autocomplete Less Functions or CSS 

### ISSUE THREAD

**Issue by sacerro** [Crunch/Crunch-2#54]
Something like Eclipse or Netbeans for autocomplete code

**Comment by nblackburn** [comment]
I like this idea but it would have to extend out to all the supported languages.

**Comment by matthew-dean** [comment]
@nblackburn - correct. It's a massive undertaking and would be probably a unique implementation per language. But I might start with Less first considering Crunch's origins.

**Comment by matthew-dean** [comment]
I notice that what Sublime does is simple word indexing. It basically indexes all the words in your file, and typing shows an autocorrect box with possible matches from that index. It's not really doing anything clever at all.

Because Less is "compile-project aware", it seems like it wouldn't be that hard to extend that index to, say, all the words across all your .less or .styl files. It would be a nice first step.

**Comment by nblackburn** [comment]
That's a solid first step which can be extended if required at a later step.

**Comment by matthew-dean** [comment]
Well, for anything not explicitly a "Crunchable", it could do that in the context of that file itself.

**Comment by matthew-dean** [comment]
@nblackburn Do you know of any simple Node library that can (intelligently) index words?

**Comment by matthew-dean** [comment]
@nblackburn Never mind, might have something cool to show you soon. :wink:

**Comment by matthew-dean** [comment]
Going to close this as autocomplete is implemented. I might open an issue later to add certain enhancements (or they'll just show up).
