### ISSUE TITLE
Add Compiler options for Stylus

### ISSUE THREAD

**Issue by nblackburn** [Crunch/Crunch-2#68]
The ability to pass options both though the GUI and the .crunch file would be a great feature as it means things like minification would be possible.

**Comment by matthew-dean** [comment]
Not sure what you mean? There are compiler options in the UI, although not options for all compilers maybe, and not necessarily all options for a particular compiler, but they're there. I'll need to go through the compiler list. In addition, yes, you can theoretically edit the .crunch JSON file directly and change options. However, that hasn't been tested, and I can't recall if it preserves extra key/value pairs or removes ones not coded for.

Here's what the options look like. I moved them inline in beta 6 to make them more discoverable.

<img width="269" alt="screen shot 2015-09-26 at 12 41 28 pm" src="https://cloud.githubusercontent.com/assets/414752/10119486/1b64ff84-644c-11e5-9013-8fdb1565d6a0.png">

**Comment by nblackburn** [comment]
Ahh, i guess there are none for Stylus :(

**Comment by matthew-dean** [comment]
Stylus has no API options? I just did a search but can't find documentation anywhere. However, gulp-stylus demonstrates some options here: https://www.npmjs.com/package/gulp-stylus. But then THAT points to accord/stylus which doesn't list options like "compress".  https://github.com/jenius/accord/blob/master/docs/stylus.md  o_O

Wait! I finally found them: https://learnboost.github.io/stylus/docs/executable.html

I find that compilers sometimes put in an option for every edge case, so what I'd like to do is support a set of "basic" or "most used" options in the Crunch UI, in order to preserve the goal of keeping Crunch simple and minimal (yet awesome), and then power users can edit the .crunch file if they want to pass in more options.

If you can take the time to compile a list of what you think are essential Stylus options out of the options listed, then I'll start there. I'll reopen this to track it.

**Comment by nblackburn** [comment]
Basically the same as the less ones. My thinking is that you could perhaps run them though a generic compiler after compiling which saves you needing compiler specific plugins for generic functionality.

**Comment by matthew-dean** [comment]
@nblackburn I've thought of that as well. However, sourcemaps definitely needs to come from the compiler options themselves, AFAIK. So, additional CSS options could come from something like Please (with all its extra e's) - http://pleeease.io/

As mentioned on #69, more than one one compiler wouldn't be in 2.0, but it would be a way to add features in the future.

**Comment by matthew-dean** [comment]
Fixed in beta 8. However, there are just two options that seemed relevant/useful: ```sourcemap``` and ```import``` (to add import paths). There are other options, yes, but they require you to write JS.

**Comment by matthew-dean** [comment]
By the way, a Stylus project looks pretty f-n cool with grouping .styl and .js files. I did grouping to support Less plugins, but it looks great here.

<img width="275" alt="screen shot 2015-10-10 at 4 25 41 pm" src="https://cloud.githubusercontent.com/assets/414752/10413793/c059bc80-6f6b-11e5-84e7-251cfeadad6f.png">
