### ISSUE TITLE
Channel closed error

### ISSUE THREAD

**Issue by TommyTheBlackbird** [Crunch/Crunch-2#70]
This message appears frequently in log panel but I still haven't figured out exactly how it affects the application.

**"Whoops! Can't watch files right now, oops. Details: Error: channel closed."**

*(Crunch 2 beta 6 / Windows 10 64bits)*

**Comment by matthew-dean** [comment]
Yeah, I know that's not the most informative of error messages. This is basically this: #51.

What's happened is the watcher process crashed. And it did so because it's a) watching a lot of files, b) watching way more files than it needs to. Previously, that would cause Crunch 2 to stop responding, but basically I'm just noting it as an error. It's the major thing I want to fix for the next beta.

How does it affect the application? Right now, it wouldn't very much. Files you have open will get Crunched when you save them. However, if you have files in your project which are not open, but change (edited somewhere else or synced through git, whatever it might be), then it will re-compile the files of your project as well. How much value that is is debatable, but it does happen right now (if the watcher process doesn't crash, of course).

The other thing that watching the directory does is update your directory tree if files get added / changed. In Crunch 1, you had to manually refresh the tree, and that always annoyed me.

Part of my discovery with Crunch 2 is that watching files is actually very non-trivial. Mac and Windows actually don't handle this very well, and have different points of failure. So it's taken a lot of work.

That's probably more verbose of an answer than you needed, but I'm like that. ^_^

**Comment by TommyTheBlackbird** [comment]
As a programmer colleague myself, it's the perfect answer for me ;)

Since there is an open issue about this #51, I close this one. I guess the debate about the need of monitoring all the files (even the those not opened in Crunch) and the recompilation of files modified out of Crunch is still open.

**Comment by matthew-dean** [comment]
Since it's the directory monitoring that's the issue, not really the other compilable files in your project, it still needs to be addressed. Even if I were to drop recompiling from external edits. Since Crunch is an editor, then maybe supporting edits from another editor doesn't really make any sense. And if it's from a change in source control, then on would assume another dev has committed their compiled file as well. So.... what do you think about that particular feature?

**Comment by matthew-dean** [comment]
This should be fixed in b7. Reopen if it pops up again
