### ISSUE TITLE
Chars not recognized in non UTF files

### ISSUE THREAD

**Issue by TommyTheBlackbird** [Crunch/Crunch-2#72]
It's seems that the editor charset is forced to UTF8 and doesn't recognize extended chars in files with other encondings (ie. Windows Cp 1252, ISO 8859 ...).

![crunch2_bug_non_utf8](https://cloud.githubusercontent.com/assets/14106278/10222874/97234e7e-6856-11e5-8816-65cdc87a7d26.png)

**Comment by matthew-dean** [comment]
Character encodings for text files is in the realm of dark arts. The encoding for any text file can't ever be determined definitively, so what text editors / IDEs typically do is put in a bunch of code to try to guess. And then, when they inevitably get it wrong, they allow you to switch the encoding.

Because UTF-8 has become a de facto web standard, and because text-encoding-guessing is a pile of work, and because I'm currently the only developer of Crunch, I would say that, unfortunately, Crunch only supports UTF-8 as the encoding. There are Node.js libraries that support saving as different encodings, but I haven't come across one that does the guessing part. Later maybe you could switch encoding, but my recommendation is just to work with UTF-8 files within Crunch.

Will close as not planned at the moment.
